/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Step = IDL.Record({
  'stepNameUrdu' : IDL.Text,
  'urduTranslation' : IDL.Text,
  'urduTransliteration' : IDL.Text,
  'stepNumber' : IDL.Nat,
  'arabicText' : IDL.Text,
  'rakaatRange' : IDL.Text,
});
export const Prayer = IDL.Record({
  'id' : IDL.Text,
  'fardRakaat' : IDL.Nat,
  'sunnahRakaat' : IDL.Nat,
  'name' : IDL.Text,
  'totalRakaat' : IDL.Nat,
  'steps' : IDL.Vec(Step),
});

export const idlService = IDL.Service({
  'getAllPrayers' : IDL.Func([], [IDL.Vec(Prayer)], ['query']),
  'getPrayer' : IDL.Func([IDL.Text], [Prayer], ['query']),
  'getPrayerSteps' : IDL.Func([IDL.Text], [IDL.Vec(Step)], ['query']),
  'initialize' : IDL.Func([], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Step = IDL.Record({
    'stepNameUrdu' : IDL.Text,
    'urduTranslation' : IDL.Text,
    'urduTransliteration' : IDL.Text,
    'stepNumber' : IDL.Nat,
    'arabicText' : IDL.Text,
    'rakaatRange' : IDL.Text,
  });
  const Prayer = IDL.Record({
    'id' : IDL.Text,
    'fardRakaat' : IDL.Nat,
    'sunnahRakaat' : IDL.Nat,
    'name' : IDL.Text,
    'totalRakaat' : IDL.Nat,
    'steps' : IDL.Vec(Step),
  });
  
  return IDL.Service({
    'getAllPrayers' : IDL.Func([], [IDL.Vec(Prayer)], ['query']),
    'getPrayer' : IDL.Func([IDL.Text], [Prayer], ['query']),
    'getPrayerSteps' : IDL.Func([IDL.Text], [IDL.Vec(Step)], ['query']),
    'initialize' : IDL.Func([], [], []),
  });
};

export const init = ({ IDL }) => { return []; };